name: Build

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
      - name: Use Install NSIS
        uses: repolevedavaj/install-nsis@v1.0.1
        with:
          nsis-version: 3.08
      - name: Run build.bat
        run: |
          .\build.bat
      - name: Build the installer
        run: |
          cmd /C "C:\Program Files (x86)\NSIS\Bin\makensis.exe" ".\installer\installer.nsi"
      - uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: installer/*.exe
