name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: i686-pc-windows-msvc
      - name: Run Rust tests
        run: |
          cd PIMELauncher
          cargo test --verbose
      - name: Use Install NSIS
        uses: repolevedavaj/install-nsis@v1.2.0
        with:
          nsis-version: 3.08
      - name: Run build.bat
        env:
          Rust_COMPILER: ${{ env.CARGO_HOME }}\bin\rustc.exe
        run: |
          .\build.bat
   
      - name: Upload unsigned binaries
        id: upload-unsigned-binaries
        uses: actions/upload-artifact@v7
        with:
          name: unsigned-binaries
          path: |
            build/PIMELauncher/PIMELauncher.exe
            build/PIMETextService/Release/PIMETextService.dll
            build64/PIMETextService/Release/PIMETextService.dll
            build_arm64/PIMETextService/Release/PIMETextService.dll

      - name: Sign binaries
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '44e7ac31-01b7-47df-8a58-44125a7d21b0'
          project-slug: 'PIME'
          signing-policy-slug: ${{ startsWith(github.ref, 'refs/tags/') && 'release-signing' || 'test-signing' }}
          artifact-configuration-slug: 'binaries-zip'
          github-artifact-id: '${{ steps.upload-unsigned-binaries.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'signed-binaries'

      - name: Replace binaries with signed versions
        run: |
          copy signed-binaries\build\PIMELauncher\PIMELauncher.exe build\PIMELauncher\PIMELauncher.exe
          copy signed-binaries\build\PIMETextService\Release\PIMETextService.dll build\PIMETextService\Release\PIMETextService.dll
          copy signed-binaries\build64\PIMETextService\Release\PIMETextService.dll build64\PIMETextService\Release\PIMETextService.dll
          copy signed-binaries\build_arm64\PIMETextService\Release\PIMETextService.dll build_arm64\PIMETextService\Release\PIMETextService.dll

      - name: Build the installer
        run: |
          cmd /C "C:\Program Files (x86)\NSIS\Bin\makensis.exe" ".\installer\installer.nsi"

      - name: Upload unsigned installer
        id: upload-unsigned-installer
        uses: actions/upload-artifact@v7
        with:
          name: unsigned-installer
          path: installer/*.exe
          archive: false  # Do not zip the NSIS installer.

      - name: Sign installer
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '44e7ac31-01b7-47df-8a58-44125a7d21b0'
          project-slug: 'PIME'
          signing-policy-slug: ${{ startsWith(github.ref, 'refs/tags/') && 'release-signing' || 'test-signing' }}
          artifact-configuration-slug: 'initial'  # The default one for single .exe files.
          github-artifact-id: '${{ steps.upload-unsigned-installer.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'signed-installer'
          skip-decompress: true  # The installer exe is not a zip file.

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: signed-installer/**/*.exe
          generate_release_notes: true
