//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ChewingTextService.rc
//
#define IDI_ICON                        101
#define ID_SWITCH_LANG                  101
#define IDI_ICON2                       102
#define IDS_CHEWING                     102
#define ID_SWITCH_SHAPE                 102
#define IDS_SWITCH_SHAPE                103
#define IDI_CHI                         103
#define IDS_SWITCH_LANG                 104
#define IDI_CONFIG                      104
#define IDI_ENG                         105
#define IDS_SETTINGS                    105
#define IDI_FULL_SHAPE                  106
#define IDS_CONFIG_TITLE                106
#define IDI_HALF_SHAPE                  107
#define IDR_MENU1                       108
#define IDR_MENU2                       109
#define IDR_MENU                        109
#define IDD_ABOUT                       121
#define IDB_COOL                        122
#define IDD_UI                          124
#define IDD_TYPING                      125
#define IDD_UPDATE                      126
#define IDD_SYMBOLS                     127
#define IDD_KEYBOARD                    135
#define IDD_EZ_SYMBOLS                  136
#define IDC_KB1                         1001
#define IDC_KB2                         1002
#define IDC_KB3                         1003
#define IDC_KB4                         1004
#define IDC_KB5                         1005
#define IDC_KB6                         1006
#define IDC_KB7                         1007
#define IDC_KB8                         1008
#define IDC_SELKEY_COLOR                1009
#define IDC_KB9                         1009
#define IDC_BUTTON1                     1009
#define IDC_CAND_PER_ROW                1010
#define IDC_BUTTON2                     1010
#define IDC_CAND_PER_ROW_SPIN           1011
#define IDC_BUTTON3                     1011
#define IDC_CAND_PER_PAGE               1012
#define IDC_BUTTON4                     1012
#define IDC_DEFAULT_ENG                 1013
#define IDC_BUTTON5                     1013
#define IDC_SELKEYS                     1014
#define IDC_BUTTON6                     1014
#define IDC_SHIFT_CAPITAL               1015
#define IDC_BUTTON7                     1015
#define IDC_CAND_COLOR2                 1016
#define IDC_SPACESEL                    1016
#define IDC_BUTTON8                     1016
#define IDC_FIX_COMPWND                 1017
#define IDC_BUTTON9                     1017
#define IDC_ADD_PHRASE_FORWARD          1018
#define IDC_BUTTON10                    1018
#define IDC_HIDE_STATUSWND              1019
#define IDC_BUTTON11                    1019
#define IDC_DEFAULT_FS                  1020
#define IDC_BUTTON12                    1020
#define IDC_ENABLE_SHIFT                1021
#define IDC_BUTTON13                    1021
#define IDC_CAND_PER_PAGE_SPIN          1022
#define IDC_BUTTON14                    1022
#define IDC_COLOR_CANDIDATE             1023
#define IDC_BUTTON15                    1023
#define IDC_BLOCK_CURSOR                1024
#define IDC_BUTTON16                    1024
#define IDC_ADV_AFTER_SEL               1025
#define IDC_BUTTON17                    1025
#define IDC_FONT_SIZE                   1026
#define IDC_SHIFT_SYMBOL                1026
#define IDC_BUTTON18                    1026
#define IDC_CTRL_SYMBOL                 1027
#define IDC_BUTTON19                    1027
#define IDC_FONT_SIZE_SPIN              1028
#define IDC_ENABLE_Simp                 1028
#define IDC_BUTTON20                    1028
#define IDC_CURSOR_CANDLIST             1029
#define IDC_BUTTON21                    1029
#define IDC_ENABLE_CAPSLOCK             1030
#define IDC_BUTTON22                    1030
#define IDC_SHIFT_FULLSHAPE             1031
#define IDC_BUTTON23                    1031
#define IDC_CHECK_NEW_VERSION           1032
#define IDC_PHRASE_MARK                 1032
#define IDC_BUTTON24                    1032
#define IDC_ESC_CLEAN_ALL_BUF           1033
#define IDC_EDIT                        1037
#define IDC_EZEDIT                      1038
#define IDC_BUTTON25                    1053
#define IDC_BUTTON26                    1054
#define IDC_BUTTON27                    1055
#define IDC_BUTTON28                    1056
#define IDC_BUTTON29                    1057
#define IDC_BUTTON30                    1058
#define IDC_BUTTON31                    1059
#define IDC_BUTTON32                    1060
#define IDC_BUTTON33                    1061
#define IDC_BUTTON35                    1063
#define IDC_BUTTON36                    1064
#define IDC_BUTTON37                    1065
#define IDC_BUTTON38                    1066
#define IDC_BUTTON39                    1067
#define IDC_BUTTON40                    1068
#define IDC_BUTTON41                    1069
#define IDC_BUTTON42                    1073
#define IDC_BUTTON43                    1074
#define ID_SETTINGS_                    40003
#define ID_ABOUT                        40005
#define ID_CHECK_NEW_VER                40006
#define ID_WEBSITE                      40007
#define ID_GROUP                        40008
#define ID_BUGREPORT                    40009
#define ID_DICT_BUGREPORT               40010
#define ID_DICT                         40011
#define ID_SIMPDICT                     40012
#define ID_LITTLEDICT                   40013
#define ID_PROVERBDICT                  40014
#define ID_CHEWING_HELP                 40015
#define ID_HASHED                       40016
#define ID_CONFIG                       40017
#define ID_EDIT_UNDO                    40018
#define ID_EDIT_CUT                     40019
#define ID_EDIT_COPY                    40020
#define ID_EDIT_PASTE                   40021
#define ID_EDIT_DELETE                  40022
#define ID_EDIT_SELALL                  40023
#define ID_40024                        40024
#define ID_MOEDICT                      40025
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40026
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
